version: '3'

services:
  grafana:
    build: ./grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - postgres

  postgres:
    container_name: garfana_postgres
    image: postgres:14.2
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "durationsdb"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:6.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@test.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-storage:/var/lib/pgadmin
      - e:\upload\avs\for_docker\:/mnt/for_docker
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  grafana-storage:
  postgres-storage:
  pgadmin-storage: